<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\iSpectrum.Core\iSpectrum.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\roms\48.rom" Link="roms\48.rom" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
